"""empty message

Revision ID: 4198553374a3
Revises: 8210d8b93ef8
Create Date: 2019-07-24 15:51:45.635696

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '4198553374a3'
down_revision = '8210d8b93ef8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'problem', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'problem', type_='foreignkey')
    op.drop_column('problem', 'category_id')
    # ### end Alembic commands ###
