"""empty message

Revision ID: 5d37dc3c78d5
Revises: 4198553374a3
Create Date: 2019-07-24 17:33:30.222475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d37dc3c78d5'
down_revision = '4198553374a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem', sa.Column('advises', sa.Text(), nullable=True))
    op.add_column('problem', sa.Column('level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problem', 'level')
    op.drop_column('problem', 'advises')
    # ### end Alembic commands ###
