"""empty message

Revision ID: 7cd2b3bfb871
Revises: 5d37dc3c78d5
Create Date: 2019-07-25 13:42:56.577294

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '7cd2b3bfb871'
down_revision = '5d37dc3c78d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem', sa.Column('theme', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problem', 'theme')
    # ### end Alembic commands ###
