"""empty message

Revision ID: 8210d8b93ef8
Revises: 6735a39fa005
Create Date: 2019-07-24 15:19:04.838756

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8210d8b93ef8'
down_revision = '6735a39fa005'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('title_ru', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('slug', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='categories_pkey'),
    sa.UniqueConstraint('number', name='categories_number_key'),
    sa.UniqueConstraint('slug', name='categories_slug_key'),
    sa.UniqueConstraint('title', name='categories_title_key'),
    sa.UniqueConstraint('title_ru', name='categories_title_ru_key')
    )
    # ### end Alembic commands ###
