"""empty message

Revision ID: a343515a01a0
Revises: 7cd2b3bfb871
Create Date: 2019-07-25 13:44:22.103387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a343515a01a0'
down_revision = '7cd2b3bfb871'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem', sa.Column('code', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problem', 'code')
    # ### end Alembic commands ###
